[package]
name = "nur"
description = "nur - a taskrunner based on nu shell"
version = "0.1.14"
edition = "2021"
license = "MIT"
homepage = "https://github.com/ddanier/nur"
repository = "https://github.com/ddanier/nur"
readme = "README.md"
authors = ["David Danier <david.danier@gmail.com>"]
keywords = ["nu", "taskrunner", "development", "command-line"]
categories = ["command-line-utilities", "development-tools"]

[dependencies]
nu-cli = "0.92.0"
nu-cmd-base = "0.92.0"
nu-cmd-dataframe = { version = "0.92.0", optional = true }
nu-cmd-extra = "0.92.0"
nu-plugin = { version = "0.92.0", optional = true }
nu-cmd-lang = "0.92.0"
nu-command = "0.92.0"
nu-engine = "0.92.0"
nu-explore = "0.92.0"
nu-parser = "0.92.0"
nu-protocol = "0.92.0"
nu-std = "0.92.0"
nu-utils = "0.92.0"
thiserror = "1.0.58"
miette = { version = "7.2", features = ["fancy-no-backtrace"] }
nu-ansi-term = "0.50.0"

[features]
default = []
dataframe = ["dep:nu-cmd-dataframe", "nu-cmd-dataframe/dataframe"]
debug = []

[dev-dependencies]
tempfile = "3.10.1"

[profile.release]
opt-level = "s"     # Optimize for size
strip = "debuginfo"
lto = "thin"
