[package]
name = "nur"
description = "nur - a taskrunner based on nu shell"
version = "0.1.8"
edition = "2021"
license = "MIT"
homepage = "https://github.com/ddanier/nur"
repository = "https://github.com/ddanier/nur"
readme = "README.md"
authors = ["David Danier <david.danier@gmail.com>"]
keywords = ["nu", "taskrunner"]
categories = ["command-line-utilities", "development-tools"]

[dependencies]
miette = { version = "7.1", features = ["fancy-no-backtrace", "fancy"] }
nu-ansi-term = "0.50.0"
nu-cli = "0.91.0"
nu-cmd-base = "0.91.0"
nu-cmd-dataframe = { version = "0.91.0", optional = true }
nu-cmd-extra = { version = "0.91.0", optional = true }
nu-cmd-lang = "0.91.0"
nu-command = "0.91.0"
nu-engine = "0.91.0"
nu-explore = "0.91.0"
nu-parser = "0.91.0"
nu-protocol = "0.91.0"
nu-std = "0.91.0"
nu-utils = "0.91.0"
thiserror = "1.0.57"

[features]
default = ["extra", "dataframe"]
extra = ["dep:nu-cmd-extra", "nu-cmd-lang/extra"]
dataframe = ["dep:nu-cmd-dataframe", "nu-cmd-dataframe/dataframe"]
debug = []

[dev-dependencies]
tempfile = "3.10.1"
