[package]
name = "n5"
version = "0.1.0"
edition = "2021"

[dependencies]
miette = "7.0.0"
nu-cli = "0.90.1"
nu-cmd-base = "0.90.1"
nu-cmd-lang = "0.90.1"
nu-command = "0.90.1"
nu-engine = "0.90.1"
nu-parser = "0.90.1"
nu-path = "0.90.1"
nu-protocol = "0.90.1"
nu-utils = "0.90.1"

[workspace]
members = [
    "crates/embed-nu",
]
