name: Create release as draft

on:
  workflow_dispatch:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*"

jobs:
  release:
    strategy:
      fail-fast: false
      matrix:
        target:
          - aarch64-apple-darwin
          - x86_64-apple-darwin
          - x86_64-pc-windows-msvc
          - aarch64-pc-windows-msvc
          - x86_64-unknown-linux-gnu
          - aarch64-unknown-linux-gnu
        format: ['bin']
        include:
          - target: aarch64-apple-darwin
            os: macos-latest
          - target: x86_64-apple-darwin
            os: macos-latest
          - target: x86_64-pc-windows-msvc
            os: windows-latest
          - target: x86_64-pc-windows-msvc
            format: msi
            os: windows-latest
          - target: aarch64-pc-windows-msvc
            os: windows-latest
          - target: aarch64-pc-windows-msvc
            format: msi
            os: windows-latest
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
          - target: aarch64-unknown-linux-gnu
            os: ubuntu-latest

    runs-on: ${{matrix.os}}
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Setup rust toolchain and cache
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          rustflags: ''  # Keep, as otherwise the defaults will be used

      - name: Setup Nushell
        uses: hustcer/setup-nu@v3.10
        with:
          version: "*"

      - name: Build nur archive
        id: build
        run: nu .github/workflows/release.nu
        env:
          OS: ${{ matrix.os }}
          TARGET: ${{ matrix.target }}
          FORMAT: ${{ matrix.format }}

      - name: Publish archives into draft release
        uses: softprops/action-gh-release@v2
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        with:
          draft: true
          name: "Release ${{ github.ref_name }}"
          generate_release_notes: true
          files: ${{ steps.build.outputs.archive }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
