name: Run nur nuscript tests

on: [push, pull_request]

jobs:
  test:
    strategy:
      fail-fast: true
      matrix:
        platform: [windows-latest, macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable

      - name: Build nur release version to be used for nur nuscript tests
        run: cargo build --release

      - name: Run nur nuscript Tests
        run: |
          cd nur-tests
          ./../target/release/nur run-all
